###
PATCH
http://localhost:3000/api/qualification/:id HTTP/1.1 (id de video)
Content-Type: application/json

{
  skills: {
  "communication":"5",
  "collaboration": "4",
  "creativity": "5",
  "critical_thinking":"5" 
  },
  "comment": "Excelente trabajo"
}