###
POST
http://localhost:3000/api/videos/upload HTTP/1.1
Content-Type: application/json

{
  "email":"some@example.com",
  "url":"www.youtube.com/watch?v=hWEOhHxHVRc&list=PLaN0VN0vnzJagadXLT8s7Amnf1i5MQSjv&index=15"
}

###
GET
http://localhost:3000/api/videos/list HTTP/1.1
Content-Type: application/json

{
}

###
GET 
http://localhost:3000/api/videos/:id HTTP/1.1 (id del usuario)

###
PATCH
http://localhost:3000/api/videos/:id HTTP/1.1 (id del video)
Content-Type: application/json

{
  "url":"www.youtube.com/watch?v=oBLyD89PfQU&list=PLaN0VN0vnzJagadXLT8s7Amnf1i5MQSjv&index=19"
}

###
DELETE
http://localhost:3000/api/videos/:id HTTP/1.1 (ide del video)